### ISSUE TITLE
Use Distribution::Resource for libraries resources

### ISSUE THREAD

**Issue by hythm7** [Xliff/p6-GLib#2]
Hello,

The `.absolute` on [this](https://github.com/Xliff/p6-GLib/blob/main/lib/GLib/Raw/Definitions.pm6#L47) line will stringify the library path, which makes the lib path hard-coded locally . instead it needs to be `$libname = %?RESOURCES{$libkey}` so `Distribution::Resource` can be used by the repositories to provide the libraries path dynamically.

More info is in [this](https://github.com/krunen/term-termios/issues/19#issuecomment-1685393313) comment.

**Comment by Xliff** [comment]
Thanks for the suggestion. This change will be made and committed, shortly.
